export default {
  onlineUsers: [
    {
      user: 105,
      username: 'fintech_founder',
      firstname: 'Vikram',
      surname: 'Bose',
      mutualUsersCount: 1,
    },
    {
      user: 102,
      username: 'macro_trader',
      firstname: 'Priya',
      surname: 'Nair',
      mutualUsersCount: 2,
    },
  ],
  conversations: [
    {
      con_id: 101,
      con_with: 105,
      con_with_username: 'fintech_founder',
      con_with_firstname: 'Vikram',
      con_with_surname: 'Bose',
      unreadMssgs: 1,
      lastMssg: {
        lastMssgTime: '1680400010000',
        lastMessage: 'Great analysis on UPI cross-border payments. Would love to collaborate.',
        lastMssgType: 'text',
        lastMssgBy: 105,
      },
    },
    {
      con_id: 102,
      con_with: 109,
      con_with_username: 'debt_monk',
      con_with_firstname: 'Suresh',
      con_with_surname: 'Rao',
      unreadMssgs: 0,
      lastMssg: {
        lastMssgTime: '1680400110000',
        lastMessage: 'Your G-Sec analysis was spot on.',
        lastMssgType: 'text',
        lastMssgBy: 102,
      },
    },
  ],
  conDetails: {
    con_id: 101,
    con_with: 105,
    con_with_username: 'fintech_founder',
    con_with_firstname: 'Vikram',
    con_with_surname: 'Bose',
    isOnline: true,
    lastOnline: '1680400000000',
  },
  conAbout: {
    mssgsCount: 2,
    media: [],
    con_time: '1680400000000',
    mutualFollowersCount: 2,
  },
  messages: [
    {
      message_id: 101,
      con_id: 101,
      mssg_by: 105,
      mssg_to: 101,
      message: 'Great analysis on UPI cross-border payments. Would love to collaborate on a detailed research note together.',
      type: 'text',
      status: 'read',
      message_time: '1680400010000',
    },
    {
      message_id: 102,
      con_id: 101,
      mssg_by: 101,
      mssg_to: 105,
      message: 'Absolutely. I have some proprietary data on NPCI transaction flows. Let us sync up this week.',
      type: 'text',
      status: 'unread',
      message_time: '1680400020000',
    },
  ],
  unreadMessages: 1,
}
