export default {
  unreadNotifications: 3,
  notifications: [
    {
      notify_id: 101,
      notify_by: 102,
      notify_by_username: 'macro_trader',
      notify_time: '1680310000100',
      type: 'follow',
      user: 0,
      user_username: '',
      post_id: 0,
      group_id: 0,
      isFollowing: true,
    },
    {
      notify_id: 102,
      notify_by: 105,
      notify_by_username: 'fintech_founder',
      notify_time: '1680314000100',
      type: 'like',
      user: 0,
      user_username: '',
      post_id: 101,
      group_id: 0,
      isFollowing: false,
    },
    {
      notify_id: 103,
      notify_by: 103,
      notify_by_username: 'growth_capital',
      notify_time: '1680312000100',
      type: 'recommend',
      user: 106,
      user_username: 'market_edge',
      post_id: 0,
      group_id: 0,
      isFollowing: false,
    },
    {
      notify_id: 104,
      notify_by: 108,
      notify_by_username: 'ai_invest',
      notify_time: '1680202200100',
      type: 'add_grp_member',
      user: 0,
      user_username: '',
      post_id: 0,
      group_id: 103,
      isFollowing: true,
    },
  ],
}
