import posts from './posts'

export default {
  feed: posts,
  posts,
  tagged: posts,
  shared: [
    {
      ...posts[0],
      share_id: 445,
      share_by_username: 'quant_alpha',
      share_time: '1680300100000',
    },
  ],
  bookmarks: [posts[0]],
  photos: [
    {
      post_id: 107,
      user: 107,
      username: 'nifty_bull',
      firstname: 'Karan',
      surname: 'Verma',
      post_time: '1680300600000',
      imgsrc: 'instagram_1516524098767.jpg',
      filter: 'filter-normal',
    },
  ],
  viewPost: {
    ...posts[0],
    comments: [
      {
        comment_id: 101,
        type: 'text',
        text: 'Strong technical setup. Volume profile confirms institutional accumulation at this level. Watch for 23,000 next.',
        commentSrc: '',
        comment_by: 102,
        comment_by_username: 'macro_trader',
        post_id: 101,
        comment_time: '1680310010000',
      },
      {
        comment_id: 102,
        type: 'text',
        text: 'PCR ratio also supportive at 1.3. Bulls firmly in control short-term.',
        commentSrc: '',
        comment_by: 108,
        comment_by_username: 'ai_invest',
        post_id: 101,
        comment_time: '1680310020000',
      },
      {
        comment_id: 103,
        type: 'text',
        text: 'HDFC CASA ratio improvement is the real story here. Lower cost of funds translates directly to sustainable NIM expansion.',
        commentSrc: '',
        comment_by: 106,
        comment_by_username: 'market_edge',
        post_id: 103,
        comment_time: '1680312010000',
      },
    ],
  },
  likes: [
    {
      like_id: 101,
      like_by: 102,
      username: 'macro_trader',
      firstname: 'Priya',
      surname: 'Nair',
      post_id: 101,
      like_time: '1680310000000',
      isFollowing: true,
    },
  ],
  tags: [
    {
      post_tag_id: 1,
      post_id: 101,
      user: 106,
      username: 'market_edge',
      firstname: 'Aisha',
      surname: 'Khan',
      isFollowing: false,
    },
  ],
  isPostMine: false,
  usersToShare: [
    {
      follow_id: 4,
      follow_to: 106,
      username: 'market_edge',
      firstname: 'Aisha',
      surname: 'Khan',
      didIShare: false,
    },
    {
      follow_id: 3,
      follow_to: 108,
      username: 'ai_invest',
      firstname: 'Diya',
      surname: 'Pillai',
      didIShare: false,
    },
  ],
  sharers: [
    {
      share_id: 103,
      share_by: 102,
      share_by_username: 'macro_trader',
      share_by_firstname: 'Priya',
      share_by_surname: 'Nair',
      share_to: 105,
      share_to_username: 'fintech_founder',
      share_time: '1680310050000',
      post_id: 101,
      isFollowing: true,
    },
  ],
  postIt: {
    fileInput: '',
    fileChanged: false,
    targetFile: '',
    previewImg: '/images/location.jpg',
    desc: '',
    filter: 'filter-normal',
    fetchingLocation: false,
    location: 'Mumbai, India',
    addTag: false,
    tags: [
      {
        user: 102,
        username: 'macro_trader',
      },
    ],
    showOverlay: false,
    type: 'user',
    group: 0,
  },
}
