export default [
  {
    post_id: 101,
    user: 101,
    username: 'quant_alpha',
    firstname: 'Arjun',
    surname: 'Sharma',
    description: 'NIFTY 50 broke through 22,500 resistance on strong FII buying. Watch for consolidation before the next leg up. #NIFTY #equity',
    imgSrc: 'instagram_1516522776339.jpg',
    filter: 'filter-normal',
    location: 'Mumbai, India',
    type: 'user',
    group_id: 0,
    post_time: '1680300000000',
    tags_count: 1,
    likes_count: 5,
    shares_count: 2,
    comments_count: 2,
    group_name: '',
  },
  {
    post_id: 103,
    user: 103,
    username: 'growth_capital',
    firstname: 'Rohan',
    surname: 'Mehta',
    description: 'HDFC Bank Q4 results strong — NIM expansion and controlled NPA. Retail lending growth at 18% YoY. Bullish at current valuations. #HDFC #banking',
    imgSrc: 'instagram_1516523813005.jpg',
    filter: 'filter-normal',
    location: 'Bengaluru, India',
    type: 'user',
    group_id: 0,
    post_time: '1680300200000',
    tags_count: 0,
    likes_count: 5,
    shares_count: 1,
    comments_count: 2,
    group_name: '',
  },
]
